### ISSUE TITLE
Wave-GUI not working

### ISSUE THREAD

**Issue by ellingtonjatwit** [ggerganov/wave-gui#1]
Hello, there is a problem with the Wave-GUI demo. 
I have tested on both a Windows 10 machine (version 1909) using Firefox (82.0) and Chrome (86.0.4240.111). The following screenshots are for Firefox and Chrome, respectively.
![Screenshot 2020-10-24 105135](https://user-images.githubusercontent.com/55757885/97084696-e5fa9c80-15e6-11eb-81f5-578be1721ec0.jpg)
![Screenshot 2020-10-24 105147](https://user-images.githubusercontent.com/55757885/97084705-ed21aa80-15e6-11eb-99d6-119f1b4991fe.jpg)

I have also tested on a MacOS machine (version 10.15.7) using Firefox (82.0) and Chrome (86.0.4240.89). The following screenshots are from Firefox and Chrome, respectively.
<img width="790" alt="Screen Shot 2020-10-24 at 10 48 48 AM" src="https://user-images.githubusercontent.com/55757885/97084848-ab453400-15e7-11eb-98c6-59ce9486ecd3.png">
<img width="788" alt="Screen Shot 2020-10-24 at 10 49 03 AM" src="https://user-images.githubusercontent.com/55757885/97084850-ada78e00-15e7-11eb-9690-0abf7f8cfa3f.png">

**Comment by ggerganov** [comment]
This should be fixed now for Chrome browsers
